# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
exclude:
  [
    CNAME,
    README.md,
    LICENSE.md,
    .gitignore,
    package.json,
    yarn.lock,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
    lint-staged.config.js,
    prettier.config.js,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: It's Wini AS
tagline: 'A Memory to capture all diary.'
keywords: 'connor, baer, bear, designer, developer, design, code, jekyll, spring'
description: 'A one-page, two-column Jekyll theme that pairs beautifully styled content with contextual media.'
url: https://wini.my.id
baseurl: '/'
assets: '/assets'
images: '/images'
logo: /ass/ets/apple-icon-144x144.png
twitter:
  username: smolcomrade
facebook:
  app_id: 169140053203395

google_analytics_key: UA-37412525-4
google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

author:
  name: Connor Bär
  url: http://wini.my.id
  email: hello@wini.my.id
  twitter: smolcomrade

social:
  twitter: https://twitter.com/smolcomrade
  instagram: https://instagram.com/smolcomrade
  github: https://github.com/ngopibrek
  medium: https://medium.com/@smolcomrade

version: 4.0.0

github:
  repo: https://github.com/connor-baer/spring

# Integrations
# typekit:              fcv7rfe

google_fonts:
  PT Sans: 400, 700
  PT Serif: 400, 700
  Playfair Display: 400

google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  Medium: https://medium.com/@connor_baer
  Twitter: https://twitter.com/connor_baer
  Github: https://github.com/connor-baer
